### ISSUE TITLE
Add bg color to header for contrast when bg img fails

### ISSUE THREAD

**Issue by livlab** [OpenNews/srccon-schedule#5]
A few times I loaded a session and the image that displays behind the header didn't load because I was an iffy connection. Not a biggie, but if that area had a background color the title would still be legible. A tiny but good accessibility improvement.

without image :(
![image](https://cloud.githubusercontent.com/assets/1936365/8366149/e3b1c8ac-1b57-11e5-9f2a-90e0b50c000c.png)
with image :)
![image](https://cloud.githubusercontent.com/assets/1936365/8366058/3ded07ba-1b57-11e5-84a7-2726f7d8f164.png)

**Comment by ryanpitts** [comment]
good call!
